version: '3.8'  #specifies docker compose version
services:
  db:
    image: postgres
    restart: always
    volumes:
    - '../postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: template
    ports:
      - "5432:5432"
  web:
    build:
      context: ./
    volumes:
      - .:/usr/src/app
    command: npm run start
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*